version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    build: 
      context: ./nginx
    ports:
      - "80:80"
    networks: 
      - nginx-front
      - global

  
  voting-app:
    image: docker/example-voting-app-vote
    container_name: voting-app
    networks: 
      - global

networks: 
  global:
  nginx-front:
